"""Add advanced saas config JSONs

Revision ID: 4986cb506276
Revises: 438631849ce6
Create Date: 2026-02-24 18:36:09.539263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4986cb506276'
down_revision: Union[str, Sequence[str], None] = '438631849ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('knowledge_base', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('billing_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'billing_info')
    op.drop_column('tenants', 'knowledge_base')
    # ### end Alembic commands ###
