"""Add assignee and priority to Task model

Revision ID: 5568193defab
Revises: e2ae933a50a5
Create Date: 2026-02-24 11:35:42.713893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5568193defab'
down_revision: Union[str, Sequence[str], None] = 'e2ae933a50a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###
