"""Add Contract model

Revision ID: ae8086673409
Revises: 895a7f6bcebd
Create Date: 2026-03-11 15:22:39.893025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8086673409'
down_revision: Union[str, Sequence[str], None] = '895a7f6bcebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_lead_id'), 'contracts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.add_column('events', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('events', sa.Column('attendant', sa.String(), nullable=True))
    op.add_column('events', sa.Column('observations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'observations')
    op.drop_column('events', 'attendant')
    op.drop_column('events', 'origin')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_lead_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
