"""Add settings fields to tenants

Revision ID: e2ae933a50a5
Revises: d4e26eb3e19c
Create Date: 2026-02-24 09:42:38.260649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ae933a50a5'
down_revision: Union[str, Sequence[str], None] = 'd4e26eb3e19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('whatsapp_number', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('sla_hours', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('welcome_message', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('ai_config', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('score_weights', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('contract_template', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('integrations', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('plan_limits', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'plan_limits')
    op.drop_column('tenants', 'integrations')
    op.drop_column('tenants', 'contract_template')
    op.drop_column('tenants', 'score_weights')
    op.drop_column('tenants', 'ai_config')
    op.drop_column('tenants', 'welcome_message')
    op.drop_column('tenants', 'sla_hours')
    op.drop_column('tenants', 'whatsapp_number')
    # ### end Alembic commands ###
